blank_issues_enabled: false
contact_links:
  - name: Discord Support
    url: https://discord.gg/your-server
    about: Get help and support from the community
  - name: Documentation
    url: https://github.com/BelugaLeagueRL/DiscordBot/wiki
    about: Check the project documentation and guides