name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-latest
    needs: []
    if: github.ref == 'refs/heads/main'
    
    environment:
      name: production
      url: https://beluga-discord-bot.your-subdomain.workers.dev
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Run linting
      run: npm run lint
      
    - name: Run type checking
      run: npm run typecheck
      
    - name: Deploy to Cloudflare Workers
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: deploy --env production
        
    - name: Wrangler Production Validation
      if: success()
      run: |
        echo "🔍 Running Wrangler-based production validation..."
        # Wait for deployment to propagate
        sleep 30
        
        # Use Wrangler's native monitoring capabilities
        node scripts/wrangler-production-validation.js
        
    - name: HTTP Production Validation  
      if: success()
      run: |
        echo "🔍 Running HTTP-based production validation..."
        
        # Run HTTP endpoint validation
        node scripts/test-production-deployment.js "${{ env.WORKER_URL || 'https://beluga-discord-bot.your-subdomain.workers.dev' }}"
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
        DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
        
    - name: Rollback on Validation Failure
      if: failure()
      run: |
        echo "💥 Production validation failed - considering rollback"
        echo "🔧 Manual intervention required to assess rollback necessity"
        echo "📋 Validation failures could indicate:"
        echo "   - Secrets not properly configured"
        echo "   - Worker runtime issues"
        echo "   - Network connectivity problems"
        echo "   - Breaking changes in deployment"

    - name: Notify Success
      if: success()
      run: |
        echo "🎉 Production deployment successful!"
        echo "✅ Bot is live and healthy at: ${{ env.HEALTH_CHECK_URL || 'https://beluga-discord-bot.your-subdomain.workers.dev' }}"
        echo "📊 Monitoring: Check Cloudflare Workers dashboard for metrics"
        
    - name: Notify Failure
      if: failure()
      run: |
        echo "💥 Production deployment failed!"
        echo "❌ Check logs above for details"
        echo "🔧 Rollback may be required"
        echo "📞 Alert: Production deployment requires immediate attention"