name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run all checks
      run: |
        npm run typecheck
        npm run lint
        npm run format:check
        npm test
        
    - name: Build check
      run: npm run build
      
    - name: Security audit
      run: npm audit --audit-level=high
      
    - name: Check for secrets
      run: |
        # Simple check for common secret patterns
        if grep -r -E "(password|secret|key|token).*=" src/ --include="*.ts" --include="*.js"; then
          echo "❌ Potential secrets found in code!"
          exit 1
        else
          echo "✅ No obvious secrets detected"
        fi